---
- name: Install required packages
  ansible.builtin.package:
    name:
      - unzip
      - tar
      - gzip
      - bzip2
    state: present

- name: Download Promtail
  ansible.builtin.get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: /tmp/promtail.zip

- name: Unzip Promtail
  ansible.builtin.unarchive:
    src: /tmp/promtail.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Make Promtail executable
  ansible.builtin.file:
    path: "{{ promtail_bin_path }}"
    mode: '0755'

- name: Ensure Promtail config directory exists
  ansible.builtin.file:
    path: "{{ promtail_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Promtail config
  ansible.builtin.template:
    src: promtail-config.yaml.j2
    dest: "{{ promtail_config_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Create Promtail service
  ansible.builtin.template:
    src: promtail.service.j2
    dest: "{{ promtail_service_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Start Promtail
  ansible.builtin.systemd:
    name: promtail
    enabled: yes
    state: started